SELECT    P.LAST_NAME,
          P.FIRST_NAME,
          C.CODE_NAME,
          L.PRIORITY_ID,
          ORS_UTIL.GET_USER_CODE(L.ADDRESS_TYPE_UID,:languageUid,:partitionUid),
          L.LOOKUP_VALUE,
          P.PERSON_NR,
          C.COMPANY_NR,
          P.COMPANY_NR,
          PC.CODE_NAME,
          DECODE(L.ADDRESS_TYPE_UID,0,0,P.DEFAULT_ADDRESS_TYPE_UID,DECODE(L.ADDRESS_COMPANY_NR,P.DEFAULT_ADDRESS_COMPANY_NR,1,P.COMPANY_NR,2,0,4,3),DECODE(L.ADDRESS_COMPANY_NR,P.COMPANY_NR,2,0,4,3))
FROM      ORS_PERSON_LOOKUP L,
          ORS_PERSON P,
          ORS_COMPANY C,
          ORS_COMPANY PC
WHERE     L.PERSON_NR = P.PERSON_NR
          AND L.ADDRESS_COMPANY_NR = C.COMPANY_NR
          AND P.COMPANY_NR = PC.COMPANY_NR
          AND L.KIND_ID = 57110
          AND P.ACTIVE = 1
          AND L.PERSON_NR=
( SELECT PERSON_NR FROM ( SELECT Z.PERSON_NR FROM ORS_PERSON_TOKEN Z WHERE Z.TOKEN_CLEAN LIKE :personNameToken0 INTERSECT ( SELECT PERSON_NR FROM ( SELECT X.PERSON_NR , P.DISPLAY_NAME FROM ORS_PERSON_LOOKUP X , ORS_PERSON P WHERE X.PERSON_NR = P.PERSON_NR AND X.ADDRESS_COMPANY_NR IN ( SELECT Z.COMPANY_NR FROM ORS_COMPANY_TOKEN Z WHERE Z.TOKEN_CLEAN LIKE :companyNameToken0 ) UNION SELECT X.PERSON_NR , X.DISPLAY_NAME FROM ORS_PERSON X WHERE X.ACTIVE = 1 AND X.COMPANY_NR IN ( SELECT Z.COMPANY_NR FROM ORS_COMPANY_TOKEN Z WHERE Z.TOKEN_CLEAN LIKE :companyNameToken0 ) ORDER BY 2 ) ) ) WHERE ROWNUM < 100 ) ORDER BY P.LAST_NAME , P.FIRST_NAME , P.PERSON_NR , C.CODE_NAME , C.COMPANY_NR
