ignoreScripts: true  # do not execute scripts (see https://pnpm.io/settings#ignorescripts)

packages:
  - 'eclipse-scout-cli'
  - 'eclipse-scout-core'
  - 'eclipse-scout-chart'
  - 'eclipse-scout-migrate'
  - 'eclipse-scout-tsconfig'
  - 'eslint-config'
  - 'karma-jasmine-scout'
  - 'org.eclipse.scout.rt.svg.ui.html'
