/*******************************************************************************
 * Copyright (c) 2010-2017 BSI Business Systems Integration AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     BSI Business Systems Integration AG - initial API and implementation
 ******************************************************************************/
package org.eclipse.scout.rt.shared.extension.dto.fixture;

import java.io.Serializable;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.extension.Extends;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.extension.dto.fixture.OrigFormWithTableFieldData.TableInOrigForm.TableInOrigFormRowData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Extends(OrigFormWithTableFieldData.class)
@Generated(value = "org.eclipse.scout.rt.shared.extension.dto.fixture.OrigFormWithTableFieldExtension", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class OrigFormWithTableFieldExtensionData extends AbstractFormFieldData {

  private static final long serialVersionUID = 1L;

  @Extends(TableInOrigFormRowData.class)
  public static class TableInOrigFormFieldExtensionRowData implements Serializable {

    private static final long serialVersionUID = 1L;
    public static final String contributedInt = "contributedInt";
    private Integer m_contributedInt;

    public Integer getContributedInt() {
      return m_contributedInt;
    }

    public void setContributedInt(Integer newContributedInt) {
      m_contributedInt = newContributedInt;
    }
  }
}
