/*
 * Copyright (c) 2010, 2024 BSI Business Systems Integration AG
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.scout.rt.shared.extension.dto.fixture;

import jakarta.annotation.Generated;

import org.eclipse.scout.rt.platform.extension.Extends;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Extends(OrigFormData.class)
@Generated(value = "org.eclipse.scout.rt.shared.extension.dto.fixture.FormPropertyExtension", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class PropertyExtensionData extends AbstractFormFieldData {
  private static final long serialVersionUID = 1L;

  /**
   * access method for property LongValue.
   */
  public Long getLongValue() {
    return getLongValueProperty().getValue();
  }

  /**
   * access method for property LongValue.
   */
  public void setLongValue(Long longValue) {
    getLongValueProperty().setValue(longValue);
  }

  public LongValueProperty getLongValueProperty() {
    return getPropertyByClass(LongValueProperty.class);
  }

  public static class LongValueProperty extends AbstractPropertyData<Long> {
    private static final long serialVersionUID = 1L;
  }
}
