package org.eclipse.scout.rt.shared.extension.dto.fixture;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.extension.Extends;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Extends(OrigFormData.class)
@Generated(value = "org.eclipse.scout.rt.shared.extension.dto.fixture.SpecialStringField", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class SpecialStringFieldData extends AbstractValueFieldData<String> {

  private static final long serialVersionUID = 1L;
}
