package org.eclipse.scout.rt.shared.extension.dto.fixture;

import java.util.Set;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.extension.Extends;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Extends(AbstractTemplateBoxData.class)
@Generated(value = "org.eclipse.scout.rt.shared.extension.dto.fixture.TreeBoxToTemplateField", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class TreeBoxToTemplateFieldData extends AbstractValueFieldData<Set<Integer>> {

  private static final long serialVersionUID = 1L;
}
