/*******************************************************************************
 * Copyright (c) 2010-2017 BSI Business Systems Integration AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     BSI Business Systems Integration AG - initial API and implementation
 ******************************************************************************/
package org.eclipse.scout.rt.client.ui.form.fields.browserfield;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.fields.browserfield.AbstractBrowserFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "org.eclipse.scout.rt.client.ui.form.fields.browserfield.AbstractBrowserFieldTest", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class AbstractBrowserFieldTestData extends AbstractBrowserFieldData {

  private static final long serialVersionUID = 1L;
}
