/*
 * Copyright (c) 2010, 2024 BSI Business Systems Integration AG
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.scout.rt.client.ui.form.fields.browserfield;

import jakarta.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.fields.browserfield.AbstractBrowserFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "org.eclipse.scout.rt.client.ui.form.fields.browserfield.AbstractBrowserFieldTest", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class AbstractBrowserFieldTestData extends AbstractBrowserFieldData {
  private static final long serialVersionUID = 1L;
}
