package org.eclipse.scout.rt.client.ui.form.fields.browserfield;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.fields.browserfield.AbstractBrowserFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "org.eclipse.scout.rt.client.ui.form.fields.browserfield.AbstractBrowserFieldTest", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class AbstractBrowserFieldTestData extends AbstractBrowserFieldData {

  private static final long serialVersionUID = 1L;
}
