/*
 * Copyright (c) 2010, 2023 BSI Business Systems Integration AG
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.scout.rt.platform.context;

import java.util.UUID;

import org.eclipse.scout.rt.platform.Bean;

/**
 * A <em>correlation ID</em> is a GUID (globally unique identifier) used to uniquely track message processing across
 * multiple systems.
 * <p>
 * Typically, a correlation ID is generated by the system which initiates processing or a request, and then is included
 * in every dependent communication. This allows to correlate log entries for that processing among system boundaries.
 *
 * @since 5.2
 */
@Bean
public class CorrelationId {

  /**
   * The <em>correlation ID</em> which is currently associated with the current thread.
   */
  public static final ThreadLocal<String> CURRENT = new ThreadLocal<>();

  /**
   * Name of the HTTP header to transport the <em>correlation ID</em>.
   */
  public static final String HTTP_HEADER_NAME = "X-Scout-Correlation-Id";

  /**
   * Generates a new <em>correlation ID</em>.
   */
  public String newCorrelationId() {
    return UUID.randomUUID().toString();
  }
}
