/*******************************************************************************
 * Copyright (c) 2010-2015 BSI Business Systems Integration AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     BSI Business Systems Integration AG - initial API and implementation
 ******************************************************************************/
package org.eclipse.scout.rt.platform.context;

import java.util.UUID;

import org.eclipse.scout.rt.platform.Bean;

/**
 * A <em>correlation ID</em> is a GUID (globally unique identifier) used to uniquely track message processing across
 * multiple systems.
 * <p>
 * Typically, a correlation ID is generated by the system which initiates processing or a request, and then is included
 * in every dependent communication. This allows to correlate log entries for that processing among system boundaries.
 *
 * @since 5.2
 */
@Bean
public class CorrelationId {

  /**
   * The <em>correlation ID</em> which is currently associated with the current thread.
   */
  public static final ThreadLocal<String> CURRENT = new ThreadLocal<>();

  /**
   * Name of the HTTP header to transport the <em>correlation ID</em>.
   */
  public static final String HTTP_HEADER_NAME = "X-Scout-Correlation-Id";

  /**
   * Generates a new <em>correlation ID</em>.
   */
  public String newCorrelationId() {
    return UUID.randomUUID().toString();
  }
}
