'use strict';

module.exports = {
  extends: ['eslint:recommended', 'google'],
  rules: {
    'indent': ['error', 2, {'SwitchCase': 1}],
    'no-extra-parens': ['warn', 'all'],
    'accessor-pairs': 'warn',
    'array-callback-return': 'error',
    'max-classes-per-file': ['error', 1],
    'no-alert': 'warn',
    'no-eval': 'error',
    'no-extra-bind': 'error',
    'no-extra-label': 'error',
    'no-implicit-coercion': 'warn',
    'no-implied-eval': 'error',
    'no-invalid-this': 'off',
    'no-iterator': 'error',
    'no-caller': 'warn',
    'no-console': 'off',
    'no-labels': 'error',
    'no-undef': 'off',
    'camelcase': ['error', {allow: ['^\\$', '_']}],
    'no-lone-blocks': 'error',
    'no-loop-func': 'error',
    'no-multi-spaces': 'error',
    'no-proto': 'error',
    'no-prototype-builtins': 'off',
    'no-return-assign': 'error',
    'eslint func-call-spacing': 'off',
    'no-return-await': 'error',
    'no-self-compare': 'error',
    'no-label-var': 'error',
    'no-shadow': 'off',
    'no-var': 'off',
    'eol-last': ['error', 'always'],
    'comma-spacing': ['error', {'before': false, 'after': true}],
    'array-bracket-spacing': ['error', 'never'],
    'brace-style': ['error', '1tbs'],
    'require-unicode-regexp': 'off',
    'no-sequences': 'error',
    'no-unmodified-loop-condition': 'error',
    'computed-property-spacing': ['error', 'never'],
    'no-useless-return': 'error',
    'no-else-return': 'warn',
    'max-len': ['error', 240, 2, {ignoreUrls: true}],
    'semi': ['error', 'always'],
    'quotes': ['error', 'single'],
    'comma-dangle': ['error', 'never'],
    'object-curly-spacing': ['error', 'never'],
    'arrow-parens': ['error', 'as-needed'],
    'arrow-spacing': 'error',
    'no-duplicate-imports': 'error',
    'one-var': 'off',
    'padded-blocks': 'off',
    'prefer-const': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'off',
    'template-curly-spacing': ['error', 'never'],
    'linebreak-style': ['error', 'unix'],
    'newline-per-chained-call': ['error', {'ignoreChainWithDepth': 2}],
    'no-lonely-if': 'error',
    'new-cap': ['error', {'capIsNewExceptions': ['Deferred']}],
    'no-multi-assign': 'error',
    'no-unused-vars': 'off',
    'require-jsdoc': 'off',
    'no-plusplus': 'off',
    'no-trailing-spaces': 'error',
    'space-before-function-paren': ['error', 'never'],
    'curly': ['error', 'all'],
    'eqeqeq': ['error', 'always', {'null': 'ignore'}],
    'spaced-comment': ['error', 'always', {'exceptions': ['*']}],
    'valid-jsdoc': 'off'
  }
};
