package org.eclipse.scout.rt.client.mobile.ui.form.fields.tabbox.fixture;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "org.eclipse.scout.rt.client.mobile.ui.form.fields.tabbox.fixture.AbstractTemplateGroupBox", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public abstract class AbstractTemplateGroupBoxData extends AbstractFormFieldData {

  private static final long serialVersionUID = 1L;

  public TabTemplate getTabTemplate() {
    return getFieldByClass(TabTemplate.class);
  }

  public Template getTemplate() {
    return getFieldByClass(Template.class);
  }

  public Text1 getText1() {
    return getFieldByClass(Text1.class);
  }

  public Text2 getText2() {
    return getFieldByClass(Text2.class);
  }

  public static class TabTemplate extends AbstractTemplate2GroupBoxData {

    private static final long serialVersionUID = 1L;
  }

  public static class Template extends AbstractTemplate3GroupBoxData {

    private static final long serialVersionUID = 1L;
  }

  public static class Text1 extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Text2 extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
