package org.eclipse.scout.rt.client.mobile.ui.form.fields.tabbox.fixture;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "org.eclipse.scout.rt.client.mobile.ui.form.fields.tabbox.fixture.AbstractTemplate3GroupBox", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public abstract class AbstractTemplate2GroupBoxData extends AbstractFormFieldData {

  private static final long serialVersionUID = 1L;

  public T3Text1 getT3Text1() {
    return getFieldByClass(T3Text1.class);
  }

  public static class T3Text1 extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
