package org.eclipse.scout.rt.client.mobile.ui.form.fields.tabbox.fixture;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "org.eclipse.scout.rt.client.mobile.ui.form.fields.tabbox.fixture.AbstractTemplate2GroupBox", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public abstract class AbstractTemplate3GroupBoxData extends AbstractFormFieldData {

  private static final long serialVersionUID = 1L;

  public T2Text1 getT2Text1() {
    return getFieldByClass(T2Text1.class);
  }

  public static class T2Text1 extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
